/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f7",
        "surface-dim": "#dadad8",
        "surface-bright": "#f9f9f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f1",
        "surface-container": "#eeeeec",
        "surface-container-high": "#e8e8e6",
        "surface-container-highest": "#e2e3e0",
        "surface-variant": "#e2e3e0",
        "surface-tint": "#2b6954",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#404944",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        outline: "#707974",
        "outline-variant": "#bfc9c3",
        primary: "#003527",
        "on-primary": "#ffffff",
        "primary-container": "#064e3b",
        "on-primary-container": "#80bea6",
        "inverse-primary": "#95d3ba",
        "primary-fixed": "#b0f0d6",
        "primary-fixed-dim": "#95d3ba",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#0b513d",
        secondary: "#775a19",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed488",
        "on-secondary-container": "#785a1a",
        "secondary-fixed": "#ffdea5",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5d4201",
        tertiary: "#2f2e28",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#46443e",
        "on-tertiary-container": "#b5b1a9",
        "tertiary-fixed": "#e7e2d9",
        "tertiary-fixed-dim": "#cac6be",
        "on-tertiary-fixed": "#1d1c16",
        "on-tertiary-fixed-variant": "#494740",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f9f9f7",
        "on-background": "#1a1c1b",
      },
      fontFamily: {
        "display-lg": ["NotoSerif_700Bold"],
        "headline-xl": ["NotoSerif_600SemiBold"],
        "headline-md": ["NotoSerif_500Medium"],
        "body-lg": ["Manrope_400Regular"],
        "body-md": ["Manrope_400Regular"],
        "label-sm": ["Manrope_600SemiBold"],
        serif: ["NotoSerif_400Regular"],
        sans: ["Manrope_400Regular"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-xl": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      spacing: {
        unit: "8px",
        "container-padding": "24px",
        gutter: "16px",
        "section-gap": "40px",
        "element-gap": "12px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
