/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // ── Active theme: Sage ──────────────────────────────────────────
        // Mirrors design/Design.md. constants/theme.ts holds the same
        // token set in JS object form for runtime (theme switching, etc.).
        bg: "#f5ede4",
        card: "#ffffff",
        primary: "#2d5a42",
        "primary-light": "#e8f0eb",
        accent: "#c8892a",
        "accent-light": "#fdf3e3",
        text: "#1e2c24",
        "text-sub": "#6b7c72",
        "tab-bg": "rgba(255,255,255,0.95)",
        "current-row": "#fdf3e3",
        "current-border": "#c8892a",

        // ── Reserved themes (preserved for a future theme picker) ───────
        // Kept by request of design/Design.md — do not delete.
        "_rose-bg": "#fdf0f3",
        "_rose-primary": "#8b1a3a",
        "_rose-primary-light": "#fde8ef",
        "_rose-accent": "#c0395a",
        "_rose-text": "#2a0e1a",
        "_rose-text-sub": "#8a6070",
        "_slate-bg": "#f0f2f5",
        "_slate-primary": "#2c3e6b",
        "_slate-primary-light": "#e8ecf5",
        "_slate-accent": "#d4862a",
        "_slate-text": "#1a2035",
        "_slate-text-sub": "#6b7590",
      },
      fontFamily: {
        // Semantic aliases per Design.md typography table.
        "app-title": ["Lora_600SemiBold"],
        "display-lg": ["Lora_700Bold"],
        "headline-xl": ["Lora_700Bold"],
        "headline-md": ["Lora_700Bold"],
        "time-lg": ["DMSans_500Medium"],
        "time-md": ["DMSans_600SemiBold"],
        "body-md": ["DMSans_600SemiBold"],
        "body-sm": ["DMSans_400Regular"],
        label: ["DMSans_700Bold"],
        caption: ["DMSans_500Medium"],
        serif: ["Lora_400Regular"],
        sans: ["DMSans_400Regular"],
      },
      fontSize: {
        "app-title": ["20px", { lineHeight: "24px", letterSpacing: "-0.3px" }],
        "display-lg": ["42px", { lineHeight: "54px" }],
        "headline-xl": ["28px", { lineHeight: "34px" }],
        "headline-md": ["24px", { lineHeight: "32px" }],
        "time-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.5px" }],
        "time-md": ["16px", { lineHeight: "22px", letterSpacing: "-0.3px" }],
        "body-md": ["15px", { lineHeight: "22px" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        label: ["12px", { lineHeight: "16px", letterSpacing: "1.5px" }],
        caption: ["13px", { lineHeight: "18px" }],
      },
      spacing: {
        "screen-pad": "20px",
        "header-pad": "24px",
        "card-pad": "20px",
        "row-pad-y": "13px",
        "row-pad-x": "16px",
        "row-gap": "8px",
        "section-gap": "24px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
        "tab-icon-bg": "10px",
        "prayer-row": "14px",
        "hero-card": "20px",
        "settings-card": "16px",
        "city-chips": "20px",
        toggle: "13px",
      },
    },
  },
  plugins: [],
};
